name: Maven Verify
on: [push,pull_request]
jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 11
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 1.11
      - name: Maven Verify
        run: mvn -B clean verify
